worldprefix: end
roundmax: 5
mob-exp-multiplier: 10
crystal-break-penalty: -200000
crystal-break-bonus: 10000
crystal-place-bonus: 25000
fishing-trash: 1000
fishing-bonus: 2000
fishing-salmon-bonus: 6000
fishing-clownfish-bonus: 100000
fishing-pufferfish-bonus: 12000
fishing-enchantbook-bonus: 150000
fishing-nametag-bonus: 150000
fishing-shell-bonus: 150000
fishing-saddle-bonus: 150000
before-world-border: 1000
stopworld: []
